import { describe, expect, it } from "vitest";
import englishMessages from "@/messages/en.json";
import spanishMessages from "@/messages/es.json";
import { creditedPackPresentationKeys, getCreditedMedia, getSinglePack } from "./packRegistry";

describe("audited Frame by Frame media", () => {
  const pack = getSinglePack("clips-single-v1")!;
  const credits = new Map(
    getCreditedMedia()
      .filter(({ packId }) => packId === "clips-single-v1")
      .map(({ media }) => [media.id, media.provenance.credit!])
  );

  it("keeps the three active videos in their final order with matching answers", () => {
    expect(pack.rounds).toHaveLength(3);
    expect(pack.rounds.map((round) => round.media.src)).toEqual([
      "/media/tutorial/videos/videos-1/r1-ai.mp4",
      "/media/tutorial/videos/videos-1/r2-real.mp4",
      "/media/tutorial/videos/videos-1/r3-ai.mp4"
    ]);
    expect(pack.rounds.map((round) => round.answer)).toEqual(["ai-generated", "camera-captured", "ai-generated"]);
    expect(pack.rounds.every((round) => round.answer === round.media.origin)).toBe(true);
  });

  it("records the falling cat as project-generated AI without an external source", () => {
    const cat = pack.rounds[0].media;

    expect(cat.origin).toBe("ai-generated");
    expect(cat.provenance).toMatchObject({ sourceType: "project-generated" });
    expect(cat.provenance.temporary).toBeUndefined();
    expect(credits.get(cat.id)).toEqual({ license: "project-generated", creationMethod: "ai-generated" });
  });

  it("credits the camera-captured cat to Pixabay under its own licence", () => {
    const cat = pack.rounds[1].media;

    expect(cat.origin).toBe("camera-captured");
    expect(cat.provenance).toMatchObject({ sourceType: "licensed", sourceName: "Pixabay", licenseStatus: "Pixabay Content License" });
    expect(cat.provenance.temporary).toBeUndefined();
    expect(credits.get(cat.id)).toMatchObject({
      title: "Orange domestic cat",
      creator: "NickyPe",
      source: "Pixabay",
      license: "Pixabay Content License"
    });
    expect(credits.get(cat.id)?.license).not.toMatch(/^CC0|CC BY/);
  });

  it("keeps the AI hand video distinct from its licensed Pexels source image", () => {
    const hand = pack.rounds[2].media;

    expect(hand.origin).toBe("ai-generated");
    expect(hand.provenance).toMatchObject({
      sourceType: "project-generated",
      sourceName: "UNESCO Youth Hackathon 2026 team",
      licenseStatus: "Generated by the team for this game"
    });
    expect(hand.provenance.temporary).toBeUndefined();
    expect(credits.get(hand.id)).toEqual({
      creationMethod: "ai-generated",
      basedOnImage: {
        title: "Persona Escribiendo En Papel Blanco",
        creator: "cottonbro studio",
        source: "Pexels",
        sourceUrl: "https://www.pexels.com/es-es/foto/persona-escribiendo-en-papel-blanco-6143818/",
        license: "Pexels License",
        licenseUrl: "https://www.pexels.com/license/"
      }
    });
  });

  it("exposes all three credits under a localized, spoiler-free pack heading", () => {
    expect([...credits.keys()]).toEqual(pack.rounds.map((round) => round.media.id));
    expect(creditedPackPresentationKeys["clips-single-v1"]).toBe("videos1");
    expect(spanishMessages.credits.packs.videos1).toBeTruthy();
    expect(englishMessages.credits.packs.videos1).toBe("Videos · Mission 1");
    expect(getCreditedMedia().filter(({ packId }) => packId === "clips-single-v1").every((item) => !("answer" in item))).toBe(true);
  });
});
